### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by dibe84** [jenkinsci/salesforce-migration-assistant-plugin#10]
Hello, I'm very interested in trying out this jenkins plugin with my org but I'm not sure if you're still working on it

**Comment by aesanch2** [comment]
@dibe84 yes its still alive 😄 

I've just been in between jobs at the moment. I'm hoping to start addressing some of the issues and adding some enhancements in the coming weeks. 

Stay tuned! 😈
