### ISSUE TITLE
Sample build file to deploy the changes using Salesforce migration assistant.

### ISSUE THREAD

**Issue by Javedmaharaja** [jenkinsci/salesforce-migration-assistant-plugin#25]
Hi All,

what is setup we need to deploy the change from repo to sfdc org? In my build setup in jenkin, I have able to configure the "Salesforce migration assistant".

I am able to get the GitSha1 id with the help of plugin but should be needed a package to deploy the change?

Thanks
Javed khan

**Comment by sanjaykharwar** [comment]
Hi Javed,

Your point is not clear to me. 
According to my current understanding if I got correct then...
You don't need do any setting in your Sales Force Org or in your Git Repository. By Default i'll take **package.xml** file available in **src/package.xml** and it also update same file according to git difference. And I think if **package.xml** is not present then it should create that according to git diff(I have not tried this scenario).

Run your job and share any issue.

Regards,
Sanjay Kharwar

**Comment by Javedmaharaja** [comment]
Thanks Sanjay for your reply,


Do you sample code to create a package.xml using git diff.

As currently, I was using package.xml to migrate the change, if you any
suggestion how to get package.xml created using git diff?


Thanks
Javed khan

**Comment by sanjaykharwar** [comment]
Hi Javed,

Seems you are not using Jenkins. This is Jenkins Plugin. You don't need to create package.xml file manually or by code. This'll done by this plugin.  Install this plugin in Jenkins(create plugin from code, official version (v2.2) have some issue) and configure it. It is very simple to configure. Follow [this link](https://github.com/jenkinsci/salesforce-migration-assistant-plugin/wiki/Configuration) and have any issue then provide details, will try to solve it.

Regards,
Sanjay Singh

**Comment by Javedmaharaja** [comment]
Hi Sanjay,

I have Jenkins and setup with git lab project, please find the setup screenshot and let me know if I missing something.

Thanks
Javed khan
![ci demo config jenkins](https://user-images.githubusercontent.com/17401084/28712753-f04c7ac4-73a9-11e7-8694-a158a42b689a.png)
![salesforce deploy gitlab 2017-07-28 15-24-39](https://user-images.githubusercontent.com/17401084/28712754-f05039c0-73a9-11e7-9d2e-3f1b296598af.png)

**Comment by sanjaykharwar** [comment]
Hi Javed,

You don't need **Invoke Ant** part. Just remove it. You need just two items. First Git Configuration according to your git server . Second part is this plugin configuration. Nothing else. For your reference I have attached screen shot of my configuration settings.

Regards,
Sanjay Kharwar

![configuration settting](https://user-images.githubusercontent.com/6229801/28717522-ca59e84a-73bf-11e7-876e-db280ce1cb91.png)

**Comment by Javedmaharaja** [comment]
Thanks Sanjay it works for me.

Thanks for your support and prompt reply on my queries.

Thanks
Javed khan

**Comment by sanjaykharwar** [comment]
glad to help you :)

**Comment by AshwiniChowdavarapu** [comment]
Hi Sanjay! I don't see Test Class Regex option:
![sfm](https://user-images.githubusercontent.com/34941196/34440034-074ef4da-ec78-11e7-8504-a19dfef63159.png)

**Comment by mayankagarwal900** [comment]
Hello Sanjay,
In my salesforce Migration Assistant I am not able to see the Test Class Regex Option Text Field. Please reply as soon as possible.

**Comment by mayankagarwal900** [comment]
Hello Sanjay,
The request is processing in the salesforce but the classes are not going in the salesforce org.
![screenshot 20](https://user-images.githubusercontent.com/43024777/50066651-0be0da00-01e3-11e9-8dc5-7f1184751538.png)

**Comment by Saikumar9959** [comment]
Hi Need help in Jenkings confiruration, i tried and its not taking the src from github its taking from my ANT build which is there in my local system .... could any one help me n this
